### ISSUE TITLE
Marketplace: filter by stars is broken

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#280] opened 2021-02-16 14:39 UTC
The filter by stars for the apps does not work properly: select 1 star, and all the apps are still visible. Select 5 stars and they still are visible but with a different order.

**Comment by pcampanella** [comment] 2021-02-19 12:13
Not agree: maybe is not clear, so we can decide how to change, but now is by design.
The filter says "X stars or MORE" so it shows all the apps that have more than 1 star + all the apps with no stars yet.
Maybe this is confusing, so we can filter the apps without stars..

**Comment by mmenapace** [comment] 2021-11-17 14:23
I think we should use the same approach used by Amazon and many other sites.
Selecting a number of start show only the review with that exactly number of stars. 
I think that "at least x stars" is misleading

The ratio behind that is "I'm curious about opinions from people that consider this good, but also I would like to highlight weakness of a product to check if, in my case for instance, these can represents a "no-go"

**Comment by mmenapace** [comment] 2021-11-17 14:56
Also thinking about that the conceptual flow is somehow wrong: 
An user search for a product that could match their requirement. After that, checks the review. So, in my opinion, reviews stars must  be showed and filtered on processor details page and not on the index of the market place.

**Comment by mmenapace** [comment] 2021-11-17 15:27
close this issue for a new enanchement proposal describing new viable behaviour

**Closed by mmenapace** 2021-11-17 15:27 UTC
Labels: bug, P3, UI / frontend, marketplace
